### ISSUE TITLE
Is this project alive, still under development?

### ISSUE THREAD

**Issue by Yann-R** [UNINETT/Foodle#64]
Hi All,
Apart from the user discussions about bug reports and feature requests, is there any further development and maintenance to hope, or this project is now asleep?
(issues seem to remain opened, pull requests are not merged...)

Nevertheless this project is very interesting. Is there any remaining people to maintain it?
Best regards.

**Comment by jaimeperez** [comment]
Hi @Yann-R!

The project is still in use in foodl.org, but as you have noticed, the development is quite dead. I've just merged some simple PRs and given feedback on others, but I have no time at all to spend on this project and I don't think Andreas is spending any time on it since a long time ago...

So if someone is willing to take over development or at least help fixing bugs, merging PRs or replying to issues, that'll be more than welcome!
